
eureka:
  client:
    register-with-eureka: false

server:
  port: 8111

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: commentservice
          uri: http://localhost:9092
          predicates:
            - Path=/comments/**
        - id: postservice
          uri: http://localhost:9091
          predicates:
            - Path=/post/**
        - id: userservice
          uri: http://localhost:9093
          predicates:
            - Path=/users/**
